classdef ToastComponents
    % TOASTCOMPONENTS - UI Drawing Helpers
    
    methods (Static)
        function btn = createProductBtn(parent, x, y, product, callback)
            theme = ToastConfig.getTheme();
            txt = sprintf('%s\n%.2f KM', product.Name, product.Price);
            
            btn = uibutton(parent, ...
                'Position', [x, y, 180, 50], ...
                'Text', txt, ...
                'BackgroundColor', theme.Button, ...
                'FontColor', theme.Text, ...
                'FontSize', 12, ...
                'ButtonPushedFcn', callback);
            
            if exist(product.ImageFile, 'file')
                btn.Icon = product.ImageFile;
                btn.IconAlignment = 'left';
            end
        end
        
        function obj = createCoinBtn(parent, x, y, value, callback)
            % Draws coins
            nameStr = sprintf('%.2f', value);
            imgName = sprintf('coin_%s.png', strrep(nameStr, '.', '_'));
            
            if exist(imgName, 'file')
                obj = uiimage(parent, ...
                    'Position', [x, y, 50, 50], ...
                    'ImageSource', imgName, ...
                    'ScaleMethod', 'fit', ...
                    'ImageClickedFcn', callback);
            else
                obj = uibutton(parent, ...
                    'Position', [x, y, 50, 50], ...
                    'Text', nameStr, ...
                    'BackgroundColor', [0.8 0.6 0.2], ...
                    'ButtonPushedFcn', callback);
            end
        end
        
        function pnl = createDarkPanel(parent, pos)
            pnl = uilabel(parent, ...
                'Position', pos, ...
                'BackgroundColor', [0.2 0.2 0.2], ...
                'FontColor', 'white', ...
                'HorizontalAlignment', 'center', ...
                'Text', '0.00');
        end
    end
end